server:
  port: 5000
spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: BOOKING-SERVICE
              uri:
                "lb://BOOKING-SERVICE"
              predicates:
                - Path= /api/bookings/**

            - id: USER-SERVICE
              uri:
                "lb://USER-SERVICE"
              predicates:
                - Path= /auth/**, /api/admin/users/**, /api/users/**, /users/**
              #filters:
              # - StripPrefix=1

            - id: SERVICE-OFFERING
              uri:
                "lb://SERVICE-OFFERING"
              predicates:
                - Path= /api/service-offering/**


            - id: SALON-SERVICE
              uri:
                "lb://SALON-SERVICE"
              predicates:
                - Path= /salons/**, /api/salons/**, /api/admin/salons/**

            - id: CATEGORY-SERVICE
              uri:
                "lb://CATEGORY-SERVICE"
              predicates:
                - Path= /api/categories/**

            - id: PAYMENT-SERVICE
              uri:
                "lb://PAYMENT-SERVICE"
              predicates:
                - Path=  /api/payments/**

  security:
    oauth2:
      resource server:
        jwt:
          jwk-set-uri: "http://localhost:8080/realms/master/protocol/openid-connect/certs"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

